name: nurani_quran
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Versi terbaru dari package http
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Menambahkan assets
  assets:
    - assets/images/arabic_pattern.png

  # Menambahkan custom fonts
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
